### ISSUE TITLE
数据集密码出错

### ISSUE THREAD

**Issue by hello11111111111111111111111** [SSTato/Meter#1]
老哥，阿里云密码出错了，能重新分享下吗？
![image](https://user-images.githubusercontent.com/48648050/197556573-dafb1cfa-b12b-4d3e-9d12-3f5c4e5a8c99.png)

**Comment by SSTato** [comment]
> 老哥，阿里云密码出错了，能重新分享下吗？ ![image](https://user-images.githubusercontent.com/48648050/197556573-dafb1cfa-b12b-4d3e-9d12-3f5c4e5a8c99.png)

数据集涉及到与其他公司的合作，暂时无法免费公开，我只能给你提供一部分我用来测试的数据。
https://www.aliyundrive.com/s/g5DT3ndTRwN
50mf

**Comment by hello11111111111111111111111** [comment]
多谢老哥








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SSTato/Meter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 上午9:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SSTato/Meter] 数据集密码出错 (Issue #1)





  
老哥，阿里云密码出错了，能重新分享下吗？ 
  
数据集涉及到与其他公司的合作，暂时无法免费公开，我只能给你提供一部分我用来测试的数据。
 https://www.aliyundrive.com/s/g5DT3ndTRwN
 50mf

**Comment by Alex-Beh** [comment]
@SSTato 
![image](https://user-images.githubusercontent.com/66585558/206856343-deeeced1-e9fa-4a06-be0f-253a177ac948.png)
