### ISSUE TITLE
老哥，能帮忙解释下类别标识的中文意义吗？

### ISSUE THREAD

**Issue by JackonLiu** [SSTato/Meter#2]
nc: 16  # number of classes  ['电流表标识','指针位置标识','电压表标识','仪表检测框','','','','','','','','','','','','','','','','','','刻度位置标识']
names: ['A', 'ZZ', 'V', 'YB', 'GUAN', 'KAI', 'BG', 'ZUO', 'ZHONG', 'YOU', 'ZD', 'TING', 'SD', 'LIANG', 'MIE', 'KD']

**Comment by SSTato** [comment]
> nc: 16 # number of classes ['电流表标识','指针位置标识','电压表标识','仪表检测框','','','','','','','','','','','','','','','','','','刻度位置标识'] names: ['A', 'ZZ', 'V', 'YB', 'GUAN', 'KAI', 'BG', 'ZUO', 'ZHONG', 'YOU', 'ZD', 'TING', 'SD', 'LIANG', 'MIE', 'KD']

电流表、指针、电压表、仪表，后面就是开关指示灯的状态了，很好理解

**Comment by JackonLiu** [comment]
A,电流表标识
ZZ,指针位置标识
V,电压表标识
YB,仪表检测框
GUAN,关
KAI,开
BG,
ZUO,左
ZHONG,中
YOU,右
SD,手动
ZD,自动
TING,停
LIANG,亮
MIE,指示灯
KD,刻度位置标识
BG是什么意思？

**Comment by SSTato** [comment]
> A,电流表标识 ZZ,指针位置标识 V,电压表标识 YB,仪表检测框 GUAN,关 KAI,开 BG, ZUO,左 ZHONG,中 YOU,右 SD,手动 ZD,自动 TING,停 LIANG,亮 MIE,指示灯 KD,刻度位置标识 BG是什么意思？

BG与KAI对应，是半挂状态，你可以理解为开和关中间的状态

**Comment by JackonLiu** [comment]
多谢老哥，可以加个联系方式聊聊吗？我们同行

**Comment by SSTato** [comment]
> 多谢老哥，可以加个联系方式聊聊吗？我们同行

我加你

**Comment by JackonLiu** [comment]
我钉钉
15869742108

**Comment by JackonLiu** [comment]
微信也一样
